default: &default
  adapter: postgresql
  encoding: utf8
  database: esi_development
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: esi_development

test: &test
  adapter: postgresql
  database: esi_test
  username: postgres
  encoding: utf8

production:
  <<: *default
  database: esi_production
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
