default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  database: esi_development
  pool: 5
  username: ubuntu
  password:

development:
  <<: *default
  database: esi_development

test: &test
  adapter: postgresql
  database: esi_test
  username: ubuntu
  encoding: SQL_ASCII

production:
  <<: *default
  database: esi_production
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
