# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a59440f3ea5b95262f0832adebef317551afcefaa85f20fdf224d1da450d9dd636b0853dbc12ef749bbf6cf652f39502a3e4d477b6f4b70cd5c89a0410cca710

test:
  secret_key_base: afc278bf9fa27d945314cb9a5321e204e9e1230bcdfc95e9f3646a3a6fc74a16c9beecce6c62fa066a247897075622d0ce7dd8a72a3b3b8c5e1e6d037f813529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
